# Generated by Django 5.1.3 on 2025-04-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='parsed_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
