# Generated by Django 5.1.3 on 2025-04-17 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_jobposting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill_gaps', models.JSONField(default=list)),
                ('formatting_suggestions', models.JSONField(default=list)),
                ('keyword_recommendations', models.JSONField(default=list)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='resume.resume')),
            ],
        ),
    ]
