# Generated by Django 5.1.3 on 2025-04-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_resumefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.JSONField(default=list),
        ),
    ]
